foundation: Ceph
url: https://ceph.github.io/ceph-membership-landscape
base_path: /ceph-membership-landscape
colors:
  color1: "rgba(240, 92, 86, 1)"
  color2: "rgba(51, 51, 51, 1)"
  color3: "rgba(51, 51, 51, 1)"
  color4: "rgba(51, 51, 51, 1)"
  color5: "rgba(51, 51, 51, 1)"
  color6: "rgba(51, 51, 51, 1)"
  color7: "rgba(51, 51, 51, 1)"
categories:
  - name: Ceph Foundation Member Company
    subcategories:
      - Premier
      - Gold
      - Silver
      - Associate
footer:
  links:
    github: https://github.com/ceph
    homepage: https://ceph.io
  logo: https://ceph.io/assets/bitmaps/Ceph_Logo_Standard_RGB_120411_fa.png
grid_items_size: large
header:
  links:
    github: https://github.com/ceph/ceph-membership-landscape
  logo: https://ceph.io/assets/bitmaps/Ceph_Logo_Standard_RGB_Reversed_120411_fa.png
screenshot_width: 1500
